name: PR Name Checker
on:
    pull_request_target:
        branches:
            - main
        types:
            - opened
            - edited

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: thehanimo/pr-title-checker@v1.4.1
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
