name: PR Name Checker
on:
    pull_request:
        branches:
            - main
        types: [edited, opened, synchronize, reopened]

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: thehanimo/pr-title-checker@v1.4.1
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - uses: cakeinpanic/jira-description-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  jira-token: ${{ secrets.JIRA_AUTH }}
                  jira-base-url: "https://tractorzoom.atlassian.net"
