name: Draft a new Release

on: workflow_dispatch

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  persist-credentials: false

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
            - name: Install dependencies
              run: |
                  yarn install

            - name: "Install Salesforce CLI"
              run: |
                  npm install @salesforce/cli --location=global
                  nodeInstallPath=$(npm config get prefix)
                  echo "$nodeInstallPath/bin" >> $GITHUB_PATH
                  sf --version

            - name: "Populate auth file with DEVHUB_SFDX_URL secret"
              run: echo ${{ secrets.DEVHUB_SFDX_URL }} > ./DEVHUB_SFDX_URL.txt

            - name: "Authenticate Dev Hub"
              run: sf org login sfdx-url -f ./DEVHUB_SFDX_URL.txt -a devhub -d

            - name: Semantic Release
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                  JIRA_AUTH: ${{ secrets.JIRA_AUTH }}
                  HUSKY: 0
              run: |
                  npx semantic-release

            # - name: "Create Package Version"
            #   run: sf package version create --package "GIFter" -x -c -w 50 -f config/project-scratch-def.json
